---
title: "cv"
output: html_document
---

## cross validation for single tree, linear model, and gam model

```{r}
# libraries
library(rpart)
library(rpart.plot)
library(tidymodels)
library(mgcv)
```


```{r}
set.seed(445)

n <- nrow(data_factor)
train_idx <- sample(seq_len(n), size = 0.8 * n)

train <- data_factor[train_idx, ]
test  <- data_factor[-train_idx, ]
target <- "Burns_Calories_per_30_min"
```


```{r}
# CV on tree model
set.seed(445)
train_cv_10fold <- vfold_cv(train, v = 5)

tree_tune_spec <- decision_tree(cost_complexity = tune("alpha")) |>
  set_engine("rpart") |>
  set_mode("regression")

tree_tune_rec <- recipe(Burns_Calories_per_30_min ~ ., data = train)

tree_wf <- workflow() |>
  add_model(tree_tune_spec) |>
  add_recipe(tree_tune_rec)

tune_data <- data.frame(alpha = 10^seq(-3, -1, length.out = 10))

tune_fit <- tree_wf |>
  tune_grid(resamples = train_cv_10fold, grid = tune_data, 
            metrics = metric_set(rmse))

tune_fit |>
  autoplot()
```

```{r}
tree_final <- finalize_workflow(tree_wf, select_best(tune_fit, metric = "rmse"))
tree_final |>
  fit(data = train) -> tree_final_fit

tree_final_fit |>
  augment(new_data = test) -> pred

metrics <- pred |>
  metric_set(rmse, mae, rsq)(
    truth = Burns_Calories_per_30_min,
    estimate = .pred
  )

metrics
```

## cv for gam model (k-fold)

```{r}
set.seed(445)
data_split <- initial_split(data, prop = 0.8)
data_train <- training(data_split)
data_test <- testing(data_split)

gam_cv_10fold <- vfold_cv(data_train, v = 5)
```

```{r}
gam_spec <- gen_additive_mod(select_features = tune("alpha")) |>
  set_engine("mgcv") |>
  set_mode("regression")

gam_formula <- calories_burned ~ 
    s(session_duration) +
    s(resting_bpm) +
    s(max_bpm) +
    experience_level +
    workout_type

exercise_gam_rec <- recipe(calories_burned ~ ., data = data_train) |>
  step_dummy(all_nominal_predictors())

exercise_gam_wf <- workflow() |>
  add_model(gam_spec, formula = gam_formula) |>
  add_recipe(exercise_gam_rec)

exercise_gam_fit <- exercise_gam_wf |>
  tune_grid(resamples = gam_cv_10fold, grid = tune_data,
            metrics = metric_set(rmse, rsq))

exercise_gam_fit |>
  autoplot()
```

```{r}
exercise_gam_final <- finalize_workflow(exercise_gam_wf, 
                                        select_best(exercise_gam_fit, metric = "rmse"))
exercise_gam_final |>
  fit(data = data_train) -> exercise_gam_final_fit

exercise_gam_final_fit |>
  augment(new_data = data_test) -> pred

metrics <- pred |>
  metric_set(rmse, mae, rsq)(
    truth = calories_burned,
    estimate = .pred)

metrics
```

## cv for exercise and diet gam

```{r}
gam_formula2 <- calories_burned ~ 
    s(session_duration) + 
    #s(avg_bpm) + 
    #s(max_bpm) + 
    s(resting_bpm) + 
    #s(weight) + 
    #s(age) + 
    #s(bmi) + 
    experience_level + 
    workout_type +
    #s(water_intake) + 
    #s(workout_frequency) + 
    #daily_meals_frequency +
    #s(carbs) + 
    #s(proteins) + 
    #s(fats) +
    diet_type

exercise_gam_rec <- recipe(calories_burned ~ ., data = data_train) |>
  step_dummy(all_nominal_predictors())

diet_gam_wf <- workflow() |>
  add_model(gam_spec, formula = gam_formula2) |>
  add_recipe(exercise_gam_rec)

diet_gam_fit <- diet_gam_wf |>
  tune_grid(resamples = gam_cv_10fold, grid = tune_data,
            metrics = metric_set(rmse, rsq))

diet_gam_fit |>
  autoplot()
```

```{r}
diet_gam_final <- finalize_workflow(diet_gam_wf, 
                                    select_best(diet_gam_fit, metric = "rmse"))
diet_gam_final |>
  fit(data = data_train) -> diet_gam_final_fit

diet_gam_final_fit |>
  augment(new_data = data_test) -> pred

metrics <- pred |>
  metric_set(rmse, mae, rsq)(
    truth = calories_burned,
    estimate = .pred)

metrics
```

## cv for linear model


 exercise: session duration, bpm metrics, reps, sets, workout type, experience level
diet: carbs, protein, fats, sugar, sodium, diet type, meal type

## exercise only

```{r}
# exercise
linear_spec <- linear_reg() |>
  set_engine("lm") |>
  set_mode("regression")

lin_formula_exercise <- calories_burned ~
    session_duration +
    resting_bpm +
    max_bpm +
    experience_level +
    workout_type

exercise_lin_rec <- recipe(calories_burned ~ ., data = data_train) |>
  step_dummy(all_nominal_predictors(), -all_outcomes())

exercise_lin_wf <- workflow() |>
  add_model(linear_spec, formula = lin_formula_exercise) |>
  add_recipe(exercise_lin_rec)

exercise_lin_fit <- exercise_lin_wf |>
  fit_resamples(resamples = gam_cv_10fold, metrics = metric_set(rmse, rsq))
```

```{r}
collect_metrics(exercise_lin_fit)
```

```{r}
# diet only
lin_formula_diet <- calories_burned ~
                    carbs + proteins +
                    fats + sugar_g +
                    sodium_mg + diet_type

diet_lin_rec <- recipe(calories_burned ~ ., data = data_train) |>
  step_dummy(all_nominal_predictors(), -all_outcomes())

diet_lin_wf <- workflow() |>
  add_model(linear_spec, formula = lin_formula_diet) |>
  add_recipe(diet_lin_rec)

diet_lin_fit <- diet_lin_wf |>
  fit_resamples(resamples = gam_cv_10fold, metrics = metric_set(rmse, rsq))
```

```{r}
collect_metrics(exercise_lin_fit)
```

```{r}
# diet and exercise

lin_formula_d_e <- calories_burned ~
                    carbs + proteins +
                    fats + sugar_g +
                    sodium_mg + diet_type +
                    session_duration +
                    resting_bpm +
                    max_bpm +
                    experience_level +
                    workout_type

d_e_lin_rec <- recipe(calories_burned ~ ., data = data_train) |>
  step_dummy(all_nominal_predictors(), -all_outcomes())

d_e_lin_wf <- workflow() |>
  add_model(linear_spec, formula = lin_formula_d_e) |>
  add_recipe(d_e_lin_rec)

d_e_lin_fit <- d_e_lin_wf |>
  fit_resamples(resamples = gam_cv_10fold, metrics = metric_set(rmse, rsq))
```

```{r}
collect_metrics(d_e_lin_fit)
```


