---
title: "GAM Model"
author: "Jessica Reyes"
date: "2025-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#libraries
library(tidyverse)
library(caret)
library(mgcv)
library(tidymodels)
library(GGally)
library(ggplot2)
library(gratia)
```

```{r}
data <- read.csv("~/STAT400/project-2/Data/new/data.csv")
head(data)
```


```{r}
# I liked this model for exercise
exercise_gam <- mgcv::gam(
  calories_burned ~ 
    s(session_duration) +
    s(resting_bpm) +
    s(max_bpm) +
    experience_level +
    workout_type,
  data = data,
  method = "GCV.Cp"
)

summary(exercise_gam)
plot(exercise_gam, pages = 1)


```

```{r}
summary(exercise_gam)


par(mfrow = c(1,3))  
plot(exercise_gam, select = 1, se = TRUE, main = "Effect of Session Duration")
plot(exercise_gam, select = 2, se = TRUE, main = "Effect of Resting BPM")
plot(exercise_gam, select = 3, se = TRUE, main = "Effect of Max BPM")

draw(exercise_gam, residuals = FALSE)
```

```{r}
#Did not love this model
diet_gam <- mgcv::gam(
  calories ~ 
    s(water_intake) +
    s(workout_frequency) +
    daily_meals_frequency +
    age +
    gender,
  data = data,
  method = "REML"
)

summary(diet_gam)
```


```{r}
draw(diet_gam)
```



```{r}
# Did not love this model --too many variables that were not meaningful
combined_gam <- mgcv::gam(
  calories_burned ~ 
    s(session_duration) + 
    s(avg_bpm) + 
    s(max_bpm) + 
    s(resting_bpm) + 
    s(weight) + 
    s(age) + 
    s(bmi) + 
    experience_level + 
    workout_type +
    s(water_intake) + 
    s(workout_frequency) + 
    daily_meals_frequency +
    s(carbs) + 
    s(proteins) + 
    s(fats) +
    diet_type,
  data = data,
  method = "REML"
)

summary(combined_gam)
plot(combined_gam, pages = 1, se = TRUE)
```
```{r}
draw(combined_gam) 
```


```{r}
#This model of the diet and exercise combined was good
combined_gam2 <- mgcv::gam(
  calories_burned ~ 
    s(session_duration) + 
    #s(avg_bpm) + 
    #s(max_bpm) + 
    s(resting_bpm) + 
    #s(weight) + 
    #s(age) + 
    #s(bmi) + 
    experience_level + 
    workout_type +
    #s(water_intake) + 
    #s(workout_frequency) + 
    #daily_meals_frequency +
    #s(carbs) + 
    #s(proteins) + 
    #s(fats) +
    diet_type,
  data = data,
  method = "REML"
)

summary(combined_gam2)
plot(combined_gam2, pages = 1, se = TRUE)
```

```{r}
draw(physio_gam2) 
```
```{r}
# from the Tree-based methods + Lab: Regression Splines + GAMs Lab
library(recipes)
library(workflows)
library(parsnip)
library(dplyr)
library(ggplot2)
library(tidymodels)

#recipe
gam_rec <- recipe(calories_burned ~ session_duration + resting_bpm + experience_level + 
                    workout_type + diet_type, data = data) %>%
  step_ns(session_duration, deg_free = 6) %>%
  step_ns(resting_bpm, deg_free = 4)

lm_spec <- linear_reg() %>% set_engine("lm")

#fit the model
gam_wf <- workflow() %>%
  add_model(lm_spec) %>%
  add_recipe(gam_rec)

gam_fit <- fit(gam_wf, data = data)

#create a grid for predictions
dat_grid <- expand.grid(
  session_duration = seq(min(data$session_duration), max(data$session_duration), length.out = 100),
  resting_bpm = seq(min(data$resting_bpm), max(data$resting_bpm), length.out = 50),
  experience_level = unique(data$experience_level),
  workout_type = unique(data$workout_type),
  diet_type = unique(data$diet_type)
)


```

```{r}
# Too many data points (hard to read)
lm_spec <- linear_reg() |> set_engine("lm")

gam_wf <- workflow() |>
  add_model(lm_spec) |>
  add_recipe(gam_rec)

gam_fit <- gam_wf |> fit(data = data)

dat_grid <- tibble(expand.grid(
  session_duration = seq(min(data$session_duration), max(data$session_duration), length.out = 100),
  resting_bpm = mean(data$resting_bpm),
  experience_level = unique(data$experience_level),
  workout_type = unique(data$workout_type),
  diet_type = unique(data$diet_type)
))


predictions <- bind_cols(dat_grid, predict(gam_fit, new_data = dat_grid))

#predictions for session_duration
session_plot <- predictions %>%
  group_by(session_duration) %>%
  summarise(.pred = mean(.pred), .groups = "drop") %>%  # predicted mean
  ggplot(aes(x = session_duration, y = .pred)) +
  geom_line(color = "rosybrown", size = 1) +
  geom_point(data = data, aes(x = session_duration, y = calories_burned), alpha = 0.3) +
  labs(y = "Calories Burned", x = "Session Duration (hours)") +
  theme_minimal()

print(session_plot)
```

