---
title: "NFL Graphs - C"
author: "Chandler"
date: "2024-12-03"
output: pdf_document
---


```{r setup, include=FALSE}
#Load the appropriate libraries:
library(ggplot2)
library(tidymodels)
library(tidyr)
library(tidyverse)
library(glmnet)
library(kknn)
library(caret)
library(kernlab)
library(nflplotR)
library(nflfastR)
library(kableExtra)
library(webshot2)
library(magick)
```


```{r rds-file-read, include=F}
svm_model_info <- readRDS("SVM Model Info by Team.rds")
```


```{r conference-mapping, include=F}
afc <- c("KC", "BUF", "PIT", "LAC", "HOU", "BAL", "DEN", "IND", "MIA", "CIN", 
         "CLE", "NYJ", "TEN", "NE", "JAX", "LV")
nfc <- c("DET", "PHI", "MIN", "GB", "WAS", "SEA", "ATL", "TB", "ARI", "LAR", 
         "SF", "DAL", "NO", "CHI", "CAR", "NYG")

```

```{r run-pass-prop, include=F}
nfl_data <- read.csv("data/modeling_data_frame.csv")

run_pass_prop <- nfl_data %>% 
  group_by(possession_team) %>% 
  summarise(tot_run = sum(run_pass == "run"),
            tot_pass = sum(run_pass == "pass")) %>% 
  ungroup() %>%
  rename(team = "possession_team")

win_loss <- read.csv("data/win_loss.csv")
```



```{r svm-df-building, include=F}
# organize teams by conference
afc <- c("KC", "BUF", "PIT", "LAC", "HOU", "BAL", "DEN", "IND", "MIA", "CIN", 
         "CLE", "NYJ", "TEN", "NE", "JAX", "LV")
nfc <- c("DET", "PHI", "MIN", "GB", "WAS", "SEA", "ATL", "TB", "ARI", "LAR", 
         "SF", "DAL", "NO", "CHI", "CAR", "NYG")

# initialize df
svm_data <- data.frame(team = unique(svm_model_info$nfl_team),
                       pass_1 = -1, pass_0 = -1, run_1 = -1, run_0 = -1,
                       mn_pvalue = 1, acc_pvalue = 1, 
                       bye_week = 0, train_error = 0, num_vec = 0,
                       spec = 0, sens = 0, pos_pred = 0, neg_pred = 0,
                       pos_class = "", conf = "")

for(i in c(1:32)){
  # get current team in data
  team <- svm_data$team[i]
  
  # get the run pass values for prediciton out of the model
  svm_data$pass_1[i] <- svm_model_info$conf_mat[[i]]$table[1,1]
  svm_data$pass_0[i] <- svm_model_info$conf_mat[[i]]$table[2,1]
  svm_data$run_1[i] <- svm_model_info$conf_mat[[i]]$table[2,2]
  svm_data$run_0[i] <- svm_model_info$conf_mat[[i]]$table[1,2]
  
  # get mcneymar p-value
  svm_data$mn_pvalue[i] <- svm_model_info$conf_mat[[i]]$overall[7]
  
  # get accuracy p-value
  svm_data$acc_pvalue[i] <- svm_model_info$conf_mat[[i]]$overall[6]
  
  # get sensitivity, specificity, possitive predicted value and negative predicted value
  svm_data$sens[i] <- svm_model_info$conf_mat[[i]]$byClass[1]
  svm_data$spec[i] <- svm_model_info$conf_mat[[i]]$byClass[2]
  svm_data$pos_pred[i] <- svm_model_info$conf_mat[[i]]$byClass[3]
  svm_data$neg_pred[i] <- svm_model_info$conf_mat[[i]]$byClass[4]
  
  # get which factor level was the "positive" class
  svm_data$pos_class[i] <- svm_model_info$conf_mat[[i]]$positive
  
  # get the bye week for each team
  svm_data$bye_week[i] <- svm_model_info$bye_week[[i]]
  
  # store the model S4 object in a temp variable for access
  temp <- svm_model_info$model[[i]] %>% extract_fit_parsnip() %>% .$fit
  
  # get model training error
  svm_data$train_error[i] <- temp@error
  
  # get number of vectors used in model
  svm_data$num_vec[i] <- temp@nSV
  
  # get the conference for each team
  svm_data$conf[i] <- ifelse(team %in% afc, "AFC", "NFC")
}

svm_data <- svm_data %>% left_join(run_pass_prop, by = "team") %>%
  left_join(win_loss, by = "team") %>%
  mutate(play_prop = ifelse(tot_run > tot_pass, "More Runs", "More Passes"),
         mcc = ((run_1 * pass_1) - (run_0 * pass_0))/ sqrt((pass_1 + pass_0) * (pass_1 + run_0) * (run_1 + pass_0) * (run_1 + run_0)),
         wining_record = ifelse(wins > losses, "Winning Team", "Losing Team"))

```

Positive class = "pass"
Negative class = "run"
Sensitivity refers to pass
Specificity refers to run

```{r spec-sens-base}
# this number will scale the image sizes proportionally
s <- 1.25
spec_sens_svm <- svm_data %>%
  ggplot(aes(y = sens, x = spec)) +
  # draw the background lines. sequence for intercept will need changing
  ggplot2::geom_abline(slope = -1, intercept = seq(2, 0.6, -0.1), alpha = .2) +
  # draw the red dashed mean lines for the data
  nflplotR::geom_mean_lines(aes(x0 = spec , y0 = sens)) +
  geom_nfl_logos(aes(team_abbr = team, width = 0.075 * s, height = 0.1 * s)) +
  labs(title = "Prediction on NFL Offenses - Run or Pass",
       subtitle = "Sensitivity and Specificity of SVM Classifier",
       y = "Pass Prediction % (Sensitivity)",
       x = "Run Prediction % (Specificity)",
       caption = "data from NFL Big Data Bowl: 2022 regular season weeks1-9") +
  theme_bw() +
  theme(
    # this just makes the background flat white
    plot.background = element_rect(fill = "white"),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 20),
    plot.subtitle = element_text(hjust = 0.5, size = 14),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 14)
  )
spec_sens_svm
```

```{r spec-sens-wins}
s <- 2
spec_sens_svm_by_winloss <- svm_data %>%
  ggplot(aes(y = sens, x = spec)) +
  facet_wrap(wining_record~., nrow = 2) +
  geom_nfl_logos(aes(team_abbr = team, width = 0.075 * s, height = 0.1 * s)) +
  labs(title = "SVM Classifier Prediction on NFL Offenses - Run or Pass",
       subtitle = "2022 Regular Season Through Week 9",
       y = "Pass Prediction % (Sensitivity)",
       x = "Run Prediction % (Specificity)",
       caption = "data from NFL Big Data Bowl") +
  theme_bw()
```

```{r mcc}
s <- 1
mcc_svm <- svm_data %>%
  ggplot(aes(y = mcc, x = team)) +
  geom_nfl_logos(aes(team_abbr = team, width = 0.075 * s, height = 0.1 * s)) +
  geom_hline(yintercept = 0, color = "red") + 
  labs(title = "Prediction on NFL Offenses - Run or Pass",
       subtitle = "MCC of SVM Classifier",
       y = "Matthews Correlation Coefficient (MCC)",
       x = "",
       caption = "data from NFL Big Data Bowl: 2022 regular season weeks1-9") +
  scale_y_continuous(limits = c(-0.3, 0.8)) +
  theme_bw() + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5, size = 14),
        axis.text.y = element_text(size = 10),
        axis.title.y = element_text(size = 14))
mcc_svm
```


```{r graph-save, eval=F, include=F}
graph_width <- 12
graph_height <- 7
ggsave("graphs/MCC for SVM.png", mcc_svm, width = graph_width, height = graph_height)

ggsave("graphs/SVM Specificity Sensitivity Graph - BW Theme.png", spec_sens_svm, width = graph_width, height = graph_height)
```


```{r other-data-load, include=F}
#rf_model_info <- readRDS("NFL_rf_models.rds")
rf_data <- read.csv("NFL_rf_results.csv")
log_model_info <- readRDS("Logistic Model Info by Team.rds")
```

```{r other-data-df-build, include=F}

#Use Chandlers code to create the appropriate data for plotting

#Create a data frame with indicators for pass and run as well as
#the Mcnemar's Test P-Value, accuracy p-value, sensitivity, specificity,etc
log_data <- data.frame(team=unique(log_model_info$nfl_team),
                       pass_1= -1, pass_0= -1, run_1=-1, run_0=-1,
                       mn_pvalue=1, acc_pvalue=1, spec=0, sens=0,
                       pos_pred=0, neg_pred=0, pos_class="")

#Calculate the values that belong in the new columns

for(i in c(1:32)){
  
  #Extract the current team
  team<- log_data$team[i]
  
  log_data$pass_1[i] <- log_model_info$conf_mat[[match(team,log_model_info$nfl_team)]]$table[1,1]
  log_data$pass_0[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$table[2,1]
  log_data$run_1[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$table[2,2]
  log_data$run_0[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$table[1,2]
  log_data$mn_pvalue[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$overall[7]
  log_data$acc_pvalue[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$overall[6]
  log_data$sens[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[1]
  log_data$spec[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[2]
  log_data$pos_pred[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[3]
  log_data$neg_pred[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[4]
  log_data$pos_class[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$positive
}
log_data <- log_data %>%
  mutate(log_mcc = ((run_1 * pass_1) - (run_0 * pass_0))/ sqrt((pass_1 + pass_0) * (pass_1 + run_0) * (run_1 + pass_0) * (run_1 + run_0)))



```



```{r summary-tables}

afc_table <- svm_data %>% rename(svm_mcc = 'mcc') %>% filter(conf == "AFC") %>%
  select(team, wins, svm_mcc) %>%
  left_join(log_data %>% select(team, log_mcc),
            by = "team") %>%
  left_join(rf_data, by = "team") %>%
  select(team, win_p, log_mcc, svm_mcc, full_MCC) %>%
  mutate(win_p = round(win_p * 100, 2)) %>%
  arrange(desc(win_p)) 

nfc_table <- svm_data %>% rename(svm_mcc = 'mcc') %>% filter(conf == "NFC") %>%
  select(team, wins, svm_mcc) %>%
  left_join(log_data %>% select(team, log_mcc),
            by = "team") %>%
  left_join(rf_data, by = "team") %>%
  select(team, win_p, log_mcc, svm_mcc, full_MCC) %>%
  mutate(win_p = round(win_p * 100, 2)) %>%
  arrange(desc(win_p)) 

nfc_table <- nfc_table %>% rowwise() %>% 
  mutate(best = max(c(log_mcc, svm_mcc, full_MCC)),
         worst = min(c(log_mcc, svm_mcc, full_MCC)))

nfc_table %>% rename("Team" = team,
                     "Win %" = win_p,
                     "Logistic MCC" = log_mcc,
                     "SVM MCC" = svm_mcc,
                     "RF MCC" = full_MCC) %>%
  select(-best, -worst) %>%
  kbl(align = rep('c', 16), format = "latex", booktabs = T) %>%
  kable_styling(font_size = 15, full_width = F) %>%
  column_spec(1, image = spec_image(teams_colors_logos$team_logo_espn[match(nfc_table$team, teams_colors_logos$team_abbr)], 75, 100)) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, bold = T, background = case_when(nfc_table$log_mcc == nfc_table$best ~ "lightgreen", 
                                                  nfc_table$log_mcc == nfc_table$worst ~ "#ff8282",
                                                  T ~ "white")) %>%
  column_spec(4, bold = T, background = case_when(nfc_table$svm_mcc == nfc_table$best ~ "lightgreen", 
                                                  nfc_table$svm_mcc == nfc_table$worst ~ "#ff8282",
                                                  T ~ "white")) %>%
  column_spec(5, bold = T, background = case_when(nfc_table$full_MCC == nfc_table$best ~ "lightgreen", 
                                                  nfc_table$full_MCC == nfc_table$worst ~ "#ff8282",
                                                  T ~ "white")) %>%
  as_image()

  save_kable(file = "NFC_Table.png", self_contained = T)

afc_table <- afc_table %>% rowwise() %>% 
  mutate(best = max(c(log_mcc, svm_mcc, full_MCC)),
         worst = min(c(log_mcc, svm_mcc, full_MCC)))

afc_table %>% rename("Team" = team,
                     "Win %" = win_p,
                     "Logistic MCC" = log_mcc,
                     "SVM MCC" = svm_mcc,
                     "RF MCC" = full_MCC) %>%
  select(-best, -worst) %>%
  kbl(align = rep('c', 16)) %>%
  kable_styling(font_size = 15, full_width = F) %>%
  column_spec(1, image = spec_image(teams_colors_logos$team_logo_espn[match(afc_table$team, teams_colors_logos$team_abbr)], 75, 100)) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, bold = T, background = case_when(afc_table$log_mcc == afc_table$best ~ "lightgreen", 
                                                  afc_table$log_mcc == afc_table$worst ~ "#ff8282",
                                                  T ~ "white")) %>%
  column_spec(4, bold = T, background = case_when(afc_table$svm_mcc == afc_table$best ~ "lightgreen", 
                                                  afc_table$svm_mcc == afc_table$worst ~ "#ff8282",
                                                  T ~ "white")) %>%
  column_spec(5, bold = T, background = case_when(afc_table$full_MCC == afc_table$best ~ "lightgreen", 
                                                  afc_table$full_MCC == afc_table$worst ~ "#ff8282",
                                                  T ~ "white")) %>%
  save_kable(file = "AFC_Table.html", self_contained = T)
  
view(teams_colors_logos)
```


