---
title: "NFL-Graphing-J"
author: "Justin C. Eldridge"
date: "2024-12-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nflplotR)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

# Graphing

## Matthews Corellation Coefficient (MCC) by Team

```{r}

#Load in the data
log_model_info <- readRDS("Logistic Model Info by Team.rds")

#Convert some of the list objects into data frames for plotting
team_names <- as.data.frame(log_model_info$nfl_team)

#Rename the column
team_names <- team_names %>%
  rename(nfl_team = `log_model_info$nfl_team`)

mcc_vals <- as.data.frame(log_model_info$m_corr)

mcc_vals_long <- mcc_vals %>%
  pivot_longer(
    cols = everything(),        
    names_to = "variable",      
    values_to = "mcc_value"     
  )

#Combine the two into a single data frame for plotting
plot_df <- data.frame(Team = team_names$nfl_team,
                      MCC = mcc_vals_long$mcc_value)

#Use the correlations in the model info list to plot correllation by team
corr_plot <- plot_df %>%
  ggplot(aes(x=Team, y=MCC))+
  
  #Add the team logos for clarity
  geom_nfl_logos(aes(team_abbr = Team,
                     width = 0.075,
                     height=0.1))+
  
  #Add a horizontal line at y=0 to visualize the boundary
  geom_hline(yintercept = 0, color="red")+
  
  #Label the two points with the highest (best) MCC
  annotate("text", x="HOU", y=0.5, label="Best Agreement",
           color="steelblue", size=6)+
  annotate("segment", 
           x="DEN", xend="BUF",
           y=0.5, yend=0.53,
           size=2,colour="steelblue",
           alpha=0.6,arrow=arrow())+
  annotate("segment", 
           x="KC", xend="NE",
           y=0.5, yend=0.45,
           size=2,colour="steelblue",
           alpha=0.6,arrow=arrow())+
  
  #Label a point where MCC is approximately 0
  #i.e. teams where the model was as good as randomly guessing
  annotate("text", x="CIN", y=0.08, label="Random Guessing",
           color="steelblue", size= 6)+
  annotate("segment", x="DEN" ,xend="HOU", y=0.05, yend=0,
           size=2, alpha=0.6,color="steelblue",
           arrow=arrow())+
  
  #Label a point with negative agreement
  annotate("text", x="CIN", y=-0.08, label="Negative Agreement",
           color="steelblue", size=6)+
  annotate("segment", x="DET" ,xend="LV", y=-0.08, yend=-0.08,
           size=2, alpha=0.6,color="steelblue",
           arrow=arrow())+
  
  #Change the y-axis limits to be consistent with the other models MCC
  scale_y_continuous(limits=c(-0.3, 0.8))+
  
  #Add appropriate labels
  labs(x="Team",
       y="Matthew Correlation Coefficient (MCC)",
       title="Prediction on NFL Offenses- Run or Pass",
       subtitle="MCC of Logistic Regression (LASSO) ",
       caption="Data from: NFL Big Data Bowl (2025)")+
  
  theme_bw()+
  
  #Adjust plot elements for neatness
  theme(plot.title= element_text(hjust=0.5, size=20),
        plot.subtitle = element_text(hjust = 0.5, size=14),
        
        #Remove the x-axis labels and ticks to clean up the plot
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y= element_text(size=14),
        axis.title.x= element_text(size=14))

#Display the plot
corr_plot

#Save the plot and put it into the graphs folder
ggsave("graphs/MCC_Logistic.png", plot=corr_plot,
       width=12, height=7)
```

## Data Cleaning
```{r}



#Use Chandlers code to create the appropriate data for plotting

#Create a data frame with indicators for pass and run as well as
#the Mcnemar's Test P-Value, accuracy p-value, sensitivity, specificity,etc
log_data <- data.frame(team=unique(log_model_info$nfl_team),
                            pass_1= -1, pass_0= -1, run_1=-1, run_0=-1,
                            mn_pvalue=1, acc_pvalue=1, spec=0, sens=0,
                            pos_pred=0, neg_pred=0, pos_class="")

#Calculate the values that belong in the new columns

for(i in c(1:32)){
  
  #Extract the current team
  team<- log_data$team[i]
  
  log_data$pass_1[i] <- log_model_info$conf_mat[[match(team,log_model_info$nfl_team)]]$table[1,1]
  log_data$pass_0[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$table[2,1]
  log_data$run_1[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$table[2,2]
  log_data$run_0[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$table[1,2]
  log_data$mn_pvalue[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$overall[7]
  log_data$acc_pvalue[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$overall[6]
  log_data$sens[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[1]
  log_data$spec[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[2]
  log_data$pos_pred[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[3]
  log_data$neg_pred[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$byClass[4]
  log_data$pos_class[i] <- log_model_info$conf_mat[[match(team, log_model_info$nfl_team)]]$positive
}

```

## Sensitivity vs. Specificity

```{r}
#Create a plot of specificity vs. sensitivity
sens_vs_spec_plot <-log_data %>%
  ggplot(aes(x = spec, y = sens)) +
  # draw the background lines. sequence for intercept will need changing
  ggplot2::geom_abline(slope = -1, intercept = seq(2, 0.6, -0.1), alpha = .2) +
  # draw the red dashed mean lines for the data
  nflplotR::geom_mean_lines(aes(x0 = spec , y0 = sens)) +
  
  #Add the team logos for clarity
  geom_nfl_logos(aes(team_abbr = team,
                     width = 0.075,
                     height=0.1))+
  
  #Add appropriate labels
  labs(x="Run Prediction % (Specificity)",
       y="Pass Prediction % (Sensitivity)",
       subtitle="Sensitivity and Specificity for Logistic Regression",
       title="Prediction on NFL Offenses-Run or Pass",
       
       #Cite the data source
       caption="Data from :National Football League (2024)")+
  theme_bw()+
  
  #Justify plot elements for neatness
  theme(plot.title= element_text(hjust=0.5, size=20),
        plot.subtitle = element_text(hjust=0.5, size=14),
        axis.title.x= element_text(size=14),
        axis.title.y= element_text(size=14)
        )

#Display the plot
sens_vs_spec_plot

#Save the plot with a width=12, height =7
ggsave("graphs/Sens_vs_spec_Logistic.png", plot=sens_vs_spec_plot,
       width=12, height=7)
```






